### ISSUE TITLE
Signal

### ISSUE THREAD

**Issue by jeffangelion** [daimoniuma/murmur#1]
So, is developer planning to add Signal support? I mean, using most secure messenger for sending already crypted messages looks pretty cool.

**Comment by daimoniuma** [comment]
Did you really ask yourself will you use it? 😸 It was planned as a simple helper for most common services which doesn't provide their own encryption: VK (Russia) & Facebook (USA), but developer said me that there are much work, and he is slightly lazy (maybe very, but tss), and it will better to do it by anyone else. I mean own messanger based on Blockchain at the end, it shouldn't be very hard for spelled programmers, especially if developer of Murmur isn't programmer (tss too). 😏

**Comment by jeffangelion** [comment]
okay
