### ISSUE TITLE
Locale changing doesn't work

### ISSUE THREAD

**Issue by HankAviator** [daimoniuma/murmur#2]
Murmur version: 0.6.3
Xposed version: v89, arm64, API 25
System: lineage os 14.1, unofficial
Device: mi 6, "sagit"

I would grab a log if I'm not on the train.
Spasibo Artem :3

**Comment by HankAviator** [comment]
And add a PayPal account in donation too!

**Comment by daimoniuma** [comment]
What? 😠 It is successfully running on my own device with Lineage 14.1.

Didn't get you about log. I need log.

1. Enable debugger in Murmur's settings.
2. Kill the app where should be changed locale.
3. Launch it.
4. Share log from Xposed Installer.

And say me if it works after screen rotation.

**Comment by HankAviator** [comment]
[murmur.log](https://github.com/daimoniuma/murmur/files/1746643/murmur.log)
I toggled SELinux too, but doesn't seem to work.
>And say me if it works after screen rotation.

No, it doesn't.

**Comment by daimoniuma** [comment]
Nothing. Try [new debug version](https://drive.google.com/file/d/150C1DlQPwvRu1lCTEDa2vfaIZA6RWI4y/view?usp=drivesdk). Give me log as previously and tell package name of application for which you changed locale.

**Comment by HankAviator** [comment]
[murmur_debug.log](https://github.com/daimoniuma/murmur/files/1747006/murmur_debug.log)
de.robv.android.xposed.installer

**Comment by daimoniuma** [comment]
You just renamed previous log. 🙄 I need new from debug version.

**Comment by HankAviator** [comment]
[murmur_debug.log](https://github.com/daimoniuma/murmur/files/1747025/murmur_debug.log)
👀 sorry

**Comment by daimoniuma** [comment]
You didn't **reload** Xposed Installer. You should completely kill app then launch it.

**Comment by HankAviator** [comment]
Tried `com.google.android.apps.freighter` this time, killed first.
[murmur_datally.log](https://github.com/daimoniuma/murmur/files/1747061/murmur_datally.log)

**Comment by daimoniuma** [comment]
Are you joking? Okay, enable debugger, reboot phone and don't disable debugger until we will end. Just launch target app and send log.

**Comment by daimoniuma** [comment]
Fixed in 0.6.4.
